# Generated by Django 5.2.5 on 2025-08-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='attendees',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
