# Generated by Django 5.2.5 on 2025-08-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('FULL', 'Whole Day'), ('EVE1', '8:30 PM - 10:00 PM'), ('EVE2', '10:00 PM - 11:30 PM')], default='FULL', max_length=10),
        ),
    ]
